version: "3.9"
services:

  # Фронтенд прокси-сервер
  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - orchestrator
      - web-client
      - browser-worker
      - browser-workers-manager
      - bull-dashboard
      - mongo-express
    networks:
      - proxy

  # Публичный HTTP API
  orchestrator:
    build: ./orchestrator
    restart: always
    depends_on:
      - redis
      - mongo
    networks:
      - proxy
      - redis

  # Графический модуль (Веб-клиент)
  web-client:
    build: ./web-client
    restart: always
    depends_on:
      - orchestrator
    networks:
      - proxy

  # 
  browser-workers-manager:
    build: ./browser-workers-manager
    restart: always
    depends_on:
      - redis
    networks:
      - redis
      - proxy

  worker:
    build: ./worker
    restart: always
    depends_on:
      - redis
    networks:
      - redis
      - mongo


  bull-dashboard:
    build: ./bull-dashboard
    restart: always
    depends_on:
      - redis
    networks:
      - redis
      - proxy

  browser-worker:
    build: ./browser-worker
    restart: always
    depends_on:
      - browser-workers-manager
    networks:
      - proxy
  
  redis:
    image: redis:alpine
    networks:
      - redis

  mongo:
    image: mongo
    restart: always
    networks:
      - mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: '*********'

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    networks:
      - proxy
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_SITE_BASEURL: /mongo-express/
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: '*********'

networks:
  proxy: {}
  mongo: {}
  redis: {}
