version: "3.9"
services:

  # Frontend Server
  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - orchestrator
      - web-client
      - browser-worker
      - browser-workers-manager
      - arena
    networks:
      - proxy-web-client
      - proxy-orchestrator
      - proxy-browser-workers-manager
      - proxy-arena
      - proxy-browser-worker

  # Public HTTP Gateway
  orchestrator:
    build: ./orchestrator
    depends_on:
      - redis
    networks:
      - proxy-orchestrator
      - redis

  # Public Web Web-client UI
  web-client:
    build: ./web-client
    depends_on:
      - orchestrator
    networks:
      - proxy-web-client
  
  browser-workers-manager:
    build: ./browser-workers-manager
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - proxy-browser-workers-manager
      - redis

  arena:
    build: ./arena
    depends_on:
      - redis
    networks:
      - redis
      - proxy-arena

  browser-worker:
    build: ./browser-worker
    depends_on:
      - browser-workers-manager
    networks:
      - proxy-browser-worker
  
  redis:
    image: "redis:alpine"
    networks:
      - redis

networks:
  proxy-web-client: {}
  proxy-orchestrator: {}
  proxy-browser-workers-manager: {}
  proxy-arena: {}
  proxy-browser-worker: {}
  redis: {}