version: "3.9"
services:

  # Frontend Server
  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - orchestrator
      - web-client
      - browser-worker
      - browser-workers-manager
      - arena
      - mongo-express
    networks:
      - proxy-web-client
      - proxy-orchestrator
      - proxy-browser-workers-manager
      - proxy-arena
      - proxy-browser-worker
      - proxy-mongo-express

  # Public HTTP Gateway
  orchestrator:
    build: ./orchestrator
    restart: always
    depends_on:
      - redis
      - mongo
    networks:
      - proxy-orchestrator
      - redis

  # Public Web Web-client UI
  web-client:
    build: ./web-client
    restart: always
    depends_on:
      - orchestrator
    networks:
      - proxy-web-client
  
  browser-workers-manager:
    build: ./browser-workers-manager
    restart: always
    depends_on:
      - redis
    networks:
      - proxy-browser-workers-manager
      - redis

  arena:
    build: ./arena
    restart: always
    depends_on:
      - redis
    networks:
      - redis
      - proxy-arena

  browser-worker:
    build: ./browser-worker
    restart: always
    depends_on:
      - browser-workers-manager
    networks:
      - proxy-browser-worker
  
  redis:
    image: redis:alpine
    networks:
      - redis

  mongo:
    image: mongo
    restart: always
    networks:
      - mongo-mongo-express
    # TODO: Add Docker secrets
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    networks:
      - proxy-mongo-express
      - mongo-mongo-express
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_SITE_BASEURL: /mongo-express/
      # TODO: Move to global config and add to Docker secrets
      # ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      # ME_CONFIG_MONGODB_ADMINPASSWORD: S0cialD@ta111!!!

networks:
  proxy-web-client: {}
  proxy-orchestrator: {}
  proxy-browser-workers-manager: {}
  proxy-arena: {}
  proxy-browser-worker: {}
  redis: {}
  proxy-mongo-express: {}
  mongo-mongo-express: {}
